version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    # depends_on:
    #   - db
    networks:
      - mysql-network
  # db:
  #   image: mysql
  #   container_name: mysql-db
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   expose:
  #     - "3306"
  #   ports:
  #     - "3306:3306"    
  #   networks:
  #     - mysql-network 
  #   volumes:
  #     - mysql-data:/var/lib/mysql     
  #   environment:
  #     MYSQL_DATABASE: nest_db
  #     MYSQL_ALLOW_EMPTY_PASSWORD: ok
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_USER: dbuser
  #     MYSQL_PASSWORD: dbuser
  #     MYSQL_ROOT_HOST: '%'
volumes:
  mysql-data:


networks:
  mysql-network:
    driver: bridge